---
# Get all recordsets
- name: Test
  hosts: localhost
  tasks:
    - name: Creating a public DNS Zone
      opentelekomcloud.cloud.dns_zones:
        name: "test.zone."
        state: present
      register: dns_zo

    - name: Creating a DNS Recordset
      opentelekomcloud.cloud.dns_recordset:
        zone_id: "{{ dns_zo.zone.id }}"
        recordset_name: "recordset.test.zone."
        type: A
        records:
          - "1.1.1.1"
          - "2.2.2.2"
        state: present
      register: dns_rs

    - name: Getting info about all allocated recordsets
      opentelekomcloud.cloud.dns_recordset_info:
        zone: "{{ dns_zo.zone.id }}"
      register: recordsets

    - name: assert result
      assert:
        that:
          - recordsets is success
          - recordsets is not changed
          - recordsets | length > 0