---
- hosts: localhost
  tasks:

    - name: Create subnet for ELB
      as_config:
        scaling_configuration_name: "as-config-test"
        key_name: "test-kp_check-ssh-between-vpcs"
        instance_id: "dbf06205-58e1-4dba-8f60-1e1bb55cee1c"
      register: as_config




