---
- name: Test Volume Snapshot
  hosts: localhost
  collections:
    - opentelekomcloud.cloud
  tasks:
    - name: Get volume snapshot info
      os_volume_snapshot_info:
      register: snapshot

    - name: Debug snapshots
      debug:
        var: snapshot
