---

- name: Query list of available host types
  opentelekomcloud.cloud.deh_host_type_info:
    az: "eu-de-01"
  register: deh_type

- name: Allocate Dedicated host
  opentelekomcloud.cloud.deh_host:
    name: "{{ deh_name }}"
    state: present
    auto_placement: True
    availability_zone: "eu-de-01"
    quantity: 1
    host_type: "s2"
    tags:
      - key: "First"
        value: "101"
  register: deh

- name: add line in vars file
  ansible.builtin.lineinfile:
    state: present
    path: "/home/yustina/git/dumb_but_brave/Ansible/otc_tests/examples_yustina/group_vars/all.yaml"
    regexp: "^deh_host_id:.*"
    insertafter: EOF
    line: "{{ ('deh_host_id: ' + deh.deh_host.dedicated_host_ids[0]) }}"
    create: True

- name: Change host name
  opentelekomcloud.cloud.deh_host:
    id: "{{ deh.deh_host.dedicated_host_ids[0] }}"
    name: "{{ deh_new_name }}"
  register: deh_change

- name: Get info about host after name changing
  opentelekomcloud.cloud.deh_host_info:
    host: "{{ deh_change.deh_host.name }}"
  register: deh_new_info

- name: Assert result
  ansible.builtin.assert:
    that:
      - deh.deh_host.name != deh_change.deh_host.name
      - deh_new_info.deh_hosts[0].name == deh_change.deh_host.name


- name: Get info about ECSs allocated on dedicated host
  opentelekomcloud.cloud.deh_server_info:
    dedicated_host: "{{ deh_change.deh_host.id }}"
